import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import '@fontsource-variable/dm-sans';
import '@fontsource/libre-caslon-display/latin-400.css';
import './styles.css';
import './quartet.css';
import './motion.css';
import './profiles/profiles.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
